// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5M4c5HMTwvJKtA--aeLWFZ-xR7mWcU2o',
    appId: '1:1044892586674:web:0b328637bdb5826a7defab',
    messagingSenderId: '1044892586674',
    projectId: 'nichesphere-777',
    authDomain: 'nichesphere-777.firebaseapp.com',
    databaseURL: 'https://nichesphere-777-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nichesphere-777.firebasestorage.app',
    measurementId: 'G-WWQQXDMVK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-sNWVDEKVQMZvFY2QdsCi0kszus5XSo8',
    appId: '1:1044892586674:android:8ce986ecb3a7e0ca7defab',
    messagingSenderId: '1044892586674',
    projectId: 'nichesphere-777',
    databaseURL: 'https://nichesphere-777-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nichesphere-777.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArUCFpxn_xAEBLfSyUXBahNrEJfJ-GEuc',
    appId: '1:1044892586674:ios:27fb2157897a2f9a7defab',
    messagingSenderId: '1044892586674',
    projectId: 'nichesphere-777',
    databaseURL: 'https://nichesphere-777-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nichesphere-777.firebasestorage.app',
    iosClientId: '1044892586674-9i03iqtl4jbh10bv5sqe6k54550dl1gv.apps.googleusercontent.com',
    iosBundleId: 'com.nichesphere.nichesphere',
  );
}
