import '../../data/models/event_model.dart';
import '../../data/models/community_model.dart';
import '../../data/models/user_model.dart';

/// Mock data for initial development (static, replaced with Firestore later)
class MockData {
  MockData._();

  static final List<EventModel> featuredEvents = [
    EventModel(
      id: '1',
      title: 'Indie Game Dev Meetup',
      description: 'Join us for a night of indie game showcases, live demos, and networking with fellow developers. Bring your prototypes!',
      category: 'Gaming',
      tags: ['gaming', 'indie', 'dev', 'networking'],
      startAt: DateTime.now().add(const Duration(days: 2, hours: 5)),
      endAt: DateTime.now().add(const Duration(days: 2, hours: 8)),
      locationName: 'The Pixel Lounge',
      locationAddress: '42 Arcade Street, Downtown',
      imageUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=600',
      attendeeCount: 47,
      maxAttendees: 60,
      organizerId: 'org1',
      organizerName: 'Pixel Guild',
      organizerAvatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100',
      createdAt: DateTime.now().subtract(const Duration(days: 5)),
      isFeatured: true,
      avgRating: 4.8,
      reviewCount: 23,
    ),
    EventModel(
      id: '2',
      title: 'Sunset Yoga in the Park',
      description: 'A peaceful sunset yoga session for all levels. Mats provided. Bring your zen energy and water bottle.',
      category: 'Fitness',
      tags: ['yoga', 'wellness', 'outdoor', 'mindfulness'],
      startAt: DateTime.now().add(const Duration(days: 1, hours: 3)),
      endAt: DateTime.now().add(const Duration(days: 1, hours: 5)),
      locationName: 'Harmony Gardens',
      locationAddress: '15 Zen Path, Riverside',
      imageUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600',
      attendeeCount: 32,
      maxAttendees: 40,
      organizerId: 'org2',
      organizerName: 'Mindful Collective',
      createdAt: DateTime.now().subtract(const Duration(days: 3)),
      isFeatured: true,
      avgRating: 4.9,
      reviewCount: 41,
    ),
    EventModel(
      id: '3',
      title: 'Watercolor Workshop',
      description: 'Learn watercolor techniques from a professional artist. All supplies included. Perfect for beginners!',
      category: 'Art',
      tags: ['art', 'watercolor', 'workshop', 'beginner'],
      startAt: DateTime.now().add(const Duration(days: 3, hours: 2)),
      endAt: DateTime.now().add(const Duration(days: 3, hours: 5)),
      locationName: 'The Art Barn',
      locationAddress: '88 Canvas Lane',
      imageUrl: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=600',
      attendeeCount: 18,
      maxAttendees: 25,
      organizerId: 'org3',
      organizerName: 'Creative Sphere',
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
      isFeatured: true,
      avgRating: 4.7,
      reviewCount: 15,
    ),
    EventModel(
      id: '4',
      title: 'Tech Talks: AI & The Future',
      description: 'A panel discussion on AI trends, ethics, and the future of work. Featuring industry leaders.',
      category: 'Tech',
      tags: ['tech', 'ai', 'panel', 'future'],
      startAt: DateTime.now().add(const Duration(days: 5)),
      endAt: DateTime.now().add(const Duration(days: 5, hours: 3)),
      locationName: 'Innovation Hub',
      locationAddress: '100 Silicon Ave',
      imageUrl: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=600',
      attendeeCount: 89,
      maxAttendees: 150,
      organizerId: 'org4',
      organizerName: 'TechSphere',
      createdAt: DateTime.now().subtract(const Duration(days: 7)),
      isFeatured: true,
      avgRating: 4.6,
      reviewCount: 34,
    ),
  ];

  static final List<EventModel> upcomingEvents = [
    EventModel(
      id: '5',
      title: 'Anime Movie Night',
      description: 'Screening of Studio Ghibli classics with popcorn and trivia.',
      category: 'Anime',
      tags: ['anime', 'movies', 'ghibli'],
      startAt: DateTime.now().add(const Duration(hours: 6)),
      endAt: DateTime.now().add(const Duration(hours: 9)),
      locationName: 'Neko Café',
      locationAddress: '3 Sakura Blvd',
      imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=600',
      attendeeCount: 24,
      maxAttendees: 30,
      organizerId: 'org5',
      organizerName: 'Otaku Hub',
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
      avgRating: 4.5,
      reviewCount: 12,
    ),
    EventModel(
      id: '6',
      title: 'Coffee Tasting Tour',
      description: 'Visit 3 local roasters and learn about single-origin beans.',
      category: 'Coffee',
      tags: ['coffee', 'tasting', 'tour'],
      startAt: DateTime.now().add(const Duration(days: 1, hours: 2)),
      endAt: DateTime.now().add(const Duration(days: 1, hours: 5)),
      locationName: 'Bean District',
      locationAddress: '7 Espresso Lane',
      imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600',
      attendeeCount: 12,
      maxAttendees: 15,
      organizerId: 'org6',
      organizerName: 'Brew Sphere',
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
      avgRating: 4.8,
      reviewCount: 8,
    ),
    EventModel(
      id: '7',
      title: 'Open Mic Night',
      description: 'Share your poetry, music, or comedy. All performers welcome!',
      category: 'Music',
      tags: ['music', 'openmic', 'performance'],
      startAt: DateTime.now().add(const Duration(days: 2, hours: 4)),
      endAt: DateTime.now().add(const Duration(days: 2, hours: 7)),
      locationName: 'Velvet Stage',
      locationAddress: '22 Melody St',
      imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600',
      attendeeCount: 55,
      maxAttendees: 80,
      organizerId: 'org7',
      organizerName: 'Sound Sphere',
      createdAt: DateTime.now().subtract(const Duration(days: 4)),
      avgRating: 4.4,
      reviewCount: 29,
    ),
  ];

  static final List<CommunityModel> communities = [
    CommunityModel(
      id: 'c1',
      name: 'Fitness Freaks',
      description: 'For those who love staying active and healthy.',
      category: 'Fitness',
      imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=200',
      memberCount: 342,
      creatorId: 'org2',
      createdAt: DateTime.now().subtract(const Duration(days: 90)),
      tags: ['fitness', 'gym', 'health'],
      activityScore: 92,
    ),
    CommunityModel(
      id: 'c2',
      name: 'Pixel Guild',
      description: 'Indie game developers and enthusiasts.',
      category: 'Gaming',
      imageUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=200',
      memberCount: 567,
      creatorId: 'org1',
      createdAt: DateTime.now().subtract(const Duration(days: 120)),
      tags: ['gaming', 'indie', 'dev'],
      activityScore: 88,
    ),
    CommunityModel(
      id: 'c3',
      name: 'Art Collective',
      description: 'Creating, sharing, and celebrating art.',
      category: 'Art',
      imageUrl: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=200',
      memberCount: 234,
      creatorId: 'org3',
      createdAt: DateTime.now().subtract(const Duration(days: 60)),
      tags: ['art', 'creative', 'painting'],
      activityScore: 75,
    ),
    CommunityModel(
      id: 'c4',
      name: 'TechSphere',
      description: 'Tech enthusiasts discussing the latest innovations.',
      category: 'Tech',
      imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=200',
      memberCount: 890,
      creatorId: 'org4',
      createdAt: DateTime.now().subtract(const Duration(days: 180)),
      tags: ['tech', 'ai', 'code'],
      activityScore: 95,
    ),
    CommunityModel(
      id: 'c5',
      name: 'Foodie Haven',
      description: 'For food lovers, home cooks, and culinary explorers.',
      category: 'Cooking',
      imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=200',
      memberCount: 456,
      creatorId: 'org6',
      createdAt: DateTime.now().subtract(const Duration(days: 45)),
      tags: ['food', 'cooking', 'recipes'],
      activityScore: 82,
    ),
  ];

  static final UserModel currentUser = UserModel(
    id: 'user1',
    name: 'Alex Rivera',
    username: 'alexr',
    email: 'alex@example.com',
    avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200',
    bio: 'Event enthusiast | Tech & Art lover | Building communities ✨',
    location: 'San Francisco, CA',
    website: 'https://alexr.dev',
    interests: ['Tech', 'Art', 'Gaming', 'Coffee', 'Music'],
    eventsHosted: 12,
    eventsAttended: 47,
    followersCount: 234,
    followingCount: 189,
    badgeIds: ['explorer_1', 'host_1', 'community_builder_1'],
    createdAt: DateTime.now().subtract(const Duration(days: 365)),
    isVerified: true,
  );
}
